# Imagen base ligera con Nginx (servidor web)
FROM nginx:alpine

# Copiar todos los archivos del proyecto al directorio público de Nginx
COPY . /usr/share/nginx/html

# Exponer el puerto 80 para el tráfico HTTP
EXPOSE 80

# El contenedor iniciará automáticamente Nginx
